---

- name: getting uri for latest artifact 
  uri:                                                               
    url: https://api.github.com/repos/HelleGazelle/forscherboard/releases/latest
    return_content: true
    headers:
      Authorization: "token {{github_oauth_token}}"                                      
  register: json_response                                             

- name: create release directory
  file:
    path: /var/www/forscherboard/releases/forscherboard-{{ json_response.json.tag_name }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Unarchive latest github release
  unarchive:
    src: https://github.com/HelleGazelle/forscherboard/releases/download/{{ json_response.json.tag_name }}/forscherboard-{{ json_response.json.tag_name }}.tar.gz

    dest: '/var/www/forscherboard/releases/forscherboard-{{ json_response.json.tag_name }}'
    remote_src: true
    extra_opts: [--strip-components=1]

- name: Create a symbolic link
  file:
    src: '/var/www/forscherboard/releases/forscherboard-{{ json_response.json.tag_name }}'
    dest: /var/www/forscherboard/current
    owner: www-data
    group: www-data
    state: link

- name: Symlink Google SAML Config
  copy:
    src: /var/www/forscherboard/configuration/GoogleSamlConfig.js
    dest: /var/www/forscherboard/current/server/GoogleSamlConfig.js
    owner: www-data
    group: www-data
    remote_src: true

- name: Symlink JIRA API credentials
  file:
    src: /var/www/forscherboard/configuration/.env
    dest: /var/www/forscherboard/current/server/.env
    owner: www-data
    group: www-data
    state: link

- name: Stop PM2 process
  command: pm2 delete Server

- name: Start server
  command: pm2 -u www-data start current/server/Server.js
  args:
    chdir: /var/www/forscherboard

- name: Saving process list
  command: "pm2 save -u www-data"
  args:
    chdir: /var/www/forscherboard/current/server/








