---

- name: getting uri for latest artifact 
  uri:                                                               
    url: https://api.github.com/repos/HelleGazelle/forscherboard/releases/latest
    return_content: true                                      
  register: json_response                                             

- name: create release directory
  file:
    path: /var/www/forscherboard/releases/forscherboard-{{ json_response.json.tag_name }}
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- name: Unarchive latest github release
  unarchive:
    src: https://github.com/HelleGazelle/forscherboard/releases/download/{{ json_response.json.tag_name }}/forscherboard-{{ json_response.json.tag_name }}.tar.gz
    dest: '/var/www/forscherboard/releases/forscherboard-{{ json_response.json.tag_name }}'
    remote_src: yes
    extra_opts: [--strip-components=1]

- name: Create a symbolic link
  file:
    src: '/var/www/forscherboard/releases/forscherboard-{{ json_response.json.tag_name }}'
    dest: /var/www/forscherboard/current
    owner: www-data
    group: www-data
    state: link






