---

- name: change var/www permissions
  file:
    path: /var/www
    owner: www-data
    group: www-data
    state: directory
    mode: '0755'

- name: create .pm2 dir
  file:
    path: /var/www/.pm2
    owner: www-data
    group: www-data
    state: directory
    mode: '0755'

- name: Generating startup script
  command: "pm2 startup systemd -u www-data --hp /var/www"

- name: Start server
  command: pm2 -u www-data start Server.js
  args:
    chdir: /var/www/forscherboard/current/server/

- name: Saving process list
  command: "pm2 save"
  args:
    chdir: /var/www/forscherboard/current/server/