name: CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          version: 12

      - name: Build Release
        run: |
          yarn install
          yarn test
          yarn build

      - name: Publish Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
